### ISSUE TITLE
docker 部署BlueLM 时遇到问题

### ISSUE THREAD

**Issue by Hapluckyy** [ssbuild/aigc_serving#119]
我在一台4090机器上使用docker部署BlueLM 模型
把模型文件通过文件挂载的方式传入了容器的 /aigc_serving/model 路径下：

config.yaml是这么写的：
```
# 配置多个模型
# 每个模型可以配置多个worker,
# 非 hf 工作模式 每个worker可以配置多个device_id

serve_args:
  host: 0.0.0.0
  port: 8081
  # http 工作进程
  workers: 1


BlueLM-7B-Chat:
  alias: null
  # 当仅有一个lora, 是否自动合并成一个模型，此方法将无法调用基础模型，只能使用合并后的权重
  auto_merge_lora_single: true
  # 是否自动量化模型
  # 是否启用
  enable: false
  # embdding max batch size
  max_batch_size: 1
  model_config:
    do_lower_case: null
    # 是否启用lora , 多个 lora , adapter_name: lora weight dir
    # "default": "/data/nlp/pre_models/torch/lora_path_dir"
    # "your_adapter_name": "/data/nlp/pre_models/torch/your_adapter_dir"
    lora: {}
    model_name_or_path: /aigc_serving/model
    model_type: BlueLM
    use_fast_tokenizer: false
  # 扩展位置长度 1 即为 1 * 2048 不扩充 , 2 即为 2 * 2 * 2048 以此类推
  ntk_scale: 1

  # one of deepspeed,accelerate,hf    单卡建议使用 hf
  work_mode: deepspeed


  workers:
  # 第一个worker
  - device_id:
    # 使用第一块和第二块显卡
    - 0
#  # 第二个worker

```

在使用api调用时，出现了错误

api调用代码：
```
import openai

openai.api_key = "EMPTY"
openai.api_base = "http://10.10.1.228:7895/v1"
model = "BlueLM"

# # Test list models API
# models = openai.Model.list()
# print("Models:", models)

# Test completion API
stream = False

data = {
    "model": model,
    "adapter_name": None, # lora头
    "prompt": ["你是谁?"],
    "top_p": 0.8,
    "temperature": 1.0,
    "frequency_penalty": 1.01,
    "stream": stream,
    "nchar": 1,# stream 字符
    "n": 1, # 返回 n 个choices
    # "stop": ["Observation:","Observation:\n"]
}


completion = openai.Completion.create(**data)
if stream:
    text = ''
    for choices in completion:
        c = choices.choices[0]
        text += c.text
        print(c.text)
    print(text)
else:
    for choice in completion.choices:
        print("result:", choice.text)

```

错误提示：
```
INFO:root:WokerLoader create...
INFO:     Started server process [316]
INFO:     Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
INFO:     10.10.1.143:54165 - "POST /v1/completions HTTP/1.1" 422 Unprocessable Entity
INFO:     10.10.1.143:54176 - "POST /v1/completions HTTP/1.1" 422 Unprocessable Entity
INFO:     10.10.1.143:54193 - "POST /v1/completions HTTP/1.1" 422 Unprocessable Entity

```

有人遇到相同的问题吗，求教
