### ISSUE TITLE
support openAI API-key

### ISSUE THREAD

**Issue by Hapluckyy** [ssbuild/aigc_serving#125]
不管是docker部署还是本地部署，我的模型权重始终没有加载进GPU
我的config.yaml文件如下：
```
# 配置多个模型
# 每个模型可以配置多个worker,
# 非 hf 工作模式 每个worker可以配置多个device_id

serve_args:
  host: 0.0.0.0
  port: 8081
  # http 工作进程
  workers: 1





Qwen-7B-Chat:
  # 当仅有一个lora, 是否自动合并成一个模型，此方法将无法调用基础模型，只能使用合并后的权重
  auto_merge_lora_single: true
  # 是否自动量化模型
  auto_quantize: false
  # 是否启用
  enable: false
  # embdding max batch size
  max_batch_size: 1
  model_config:
    do_lower_case: null
    # 是否启用lora , 多个 lora , adapter_name: lora weight dir
    # "default": "/data/nlp/pre_models/torch/lora_path_dir"
    # "your_adapter_name": "/data/nlp/pre_models/torch/your_adapter_dir"
    lora: {}
    model_name_or_path:/home/edge2/model/Qwen7b
    model_type: qwen
    use_fast_tokenizer: false

  # one of deepspeed,accelerate,hf    单卡建议使用 hf
  work_mode: hf


  workers:
  # 第一个worker
  - device_id:
    # 使用第一块和第二块显卡
    - 0
#  # 第二个worker
#  - device_id:
#    # 使用第三块和第四块显卡
#    - 2
#    - 3

```
运行
bash start.sh
不会有报错，输出如下：
```
(base) edge2@edge2:~/code/aigc_server/aigc_serving/script$ bash start.sh
/home/edge2/miniconda3/lib/python3.11/site-packages/pydantic/_internal/_config.py:318: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
INFO:root:WokerLoader create...
INFO:     Started server process [126800]
INFO:     Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
```

使用api调用该接口时，有如下报错：
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File [c:\Users\haplucky\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py:403](file:///C:/Users/haplucky/AppData/Local/Programs/Python/Python311/Lib/site-packages/openai/api_requestor.py:403), in APIRequestor.handle_error_response(self, rbody, rcode, resp, rheaders, stream_error)
    [402](file:///C:/Users/haplucky/AppData/Local/Programs/Python/Python311/Lib/site-packages/openai/api_requestor.py:402) try:
--> [403](file:///C:/Users/haplucky/AppData/Local/Programs/Python/Python311/Lib/site-packages/openai/api_requestor.py:403)     error_data = resp["error"]
    [404](file:///C:/Users/haplucky/AppData/Local/Programs/Python/Python311/Lib/site-packages/openai/api_requestor.py:404) except (KeyError, TypeError):

KeyError: 'error'

During handling of the above exception, another exception occurred:

APIError                                  Traceback (most recent call last)
[e:\llm-api\blue_lm_test.ipynb](file:///E:/llm-api/blue_lm_test.ipynb) 单元格 1 line 2
     [13](vscode-notebook-cell:/e%3A/llm-api/blue_lm_test.ipynb#W0sZmlsZQ%3D%3D?line=12) stream = False
     [15](vscode-notebook-cell:/e%3A/llm-api/blue_lm_test.ipynb#W0sZmlsZQ%3D%3D?line=14) data = {
     [16](vscode-notebook-cell:/e%3A/llm-api/blue_lm_test.ipynb#W0sZmlsZQ%3D%3D?line=15)     "model": model,
     [17](vscode-notebook-cell:/e%3A/llm-api/blue_lm_test.ipynb#W0sZmlsZQ%3D%3D?line=16)     "adapter_name": None, # lora头
   (...)
     [25](vscode-notebook-cell:/e%3A/llm-api/blue_lm_test.ipynb#W0sZmlsZQ%3D%3D?line=24)     # "stop": ["Observation:","Observation:\n"]
     [26](vscode-notebook-cell:/e%3A/llm-api/blue_lm_test.ipynb#W0sZmlsZQ%3D%3D?line=25) }
---> [29](vscode-notebook-cell:/e%3A/llm-api/blue_lm_test.ipynb#W0sZmlsZQ%3D%3D?line=28) completion = openai.Completion.create(**data)
     [30](vscode-notebook-cell:/e%3A/llm-api/blue_lm_test.ipynb#W0sZmlsZQ%3D%3D?line=29) if stream:
     [31](vscode-notebook-cell:/e%3A/llm-api/blue_lm_test.ipynb#W0sZmlsZQ%3D%3D?line=30)     text = ''

File [c:\Users\haplucky\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\completion.py:25](file:///C:/Users/haplucky/AppData/Local/Programs/Python/Python311/Lib/site-packages/openai/api_resources/completion.py:25), in Completion.create(cls, *args, **kwargs)
...
    [411](file:///C:/Users/haplucky/AppData/Local/Programs/Python/Python311/Lib/site-packages/openai/api_requestor.py:411)     )
    [413](file:///C:/Users/haplucky/AppData/Local/Programs/Python/Python311/Lib/site-packages/openai/api_requestor.py:413) if "internal_message" in error_data:
    [414](file:///C:/Users/haplucky/AppData/Local/Programs/Python/Python311/Lib/site-packages/openai/api_requestor.py:414)     error_data["message"] += "\n\n" + error_data["internal_message"]

APIError: Invalid response object from API: '{"object":"error","message":"qwen-7b-chat Invalid model: model not in []","code":40301}' (HTTP response code was 500)
```

使用nvidia-smi检查发现，显卡显存中并没有加载模型权重
请问大家有遇到相同的问题吗？

求解，谢谢~
